Feature/team arch backend merge2
umgc/summer2022 pull request #15
Opened 2022-07-09 11:03 UTC by stanley-dejesus

- Added Backend Features -> Google Vision OCR, Logo, & QR Detection
- Updated Images used for unit testing
- Added a separate route and button for accessing the backend test page. The button is located on the main menu page
- Updated Backend GUI to reflect Application UI appearance
- Below is the setup guide for obtaining your Cloud Vision credentials.

[How to setup Google Cloud Vision API and get credential key](https://github.com/umgc/summer2022/files/9076335/How.to.setup.Google.Cloud.Vision.API.and.get.credential.key.docx)

2022-07-10 23:51 UTC, zsloan112 requested changes
Changes are very minor, mainly adding things to .gitignore that don't need to be in source control and deleting this from the source

2022-07-10 23:51 UTC, zsloan112 commented on .flutter-plugins 2
> +# This is a generated file; do not edit or check into version control.
Ensure this is added to the .gitignore file since it says it should not be checked in.

2022-07-10 23:51 UTC, zsloan112 commented on .vscode/launch.json
> +{
Recommend adding this to .gitignore as well.

2022-07-10 23:51 UTC, zsloan112 commented on android/local.properties
> +sdk.dir=C:\\SDK\\Android
Believe this should be in .gitignore as well.

2022-07-10 23:51 UTC, zsloan112 commented on .flutter-plugins 2
> +# This is a generated file; do not edit or check into version control.
Add to gitignore and remove from source control

2022-07-10 23:51 UTC, zsloan112 commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Add to .idea folder to .gitignore and remove from source control

2022-07-10 23:51 UTC, zsloan112 commented on summer2022.iml
> -<?xml version="1.0" encoding="UTF-8"?>
If this file is empty, I would recommend deleting it and/or adding to .gitignore

2022-07-11 01:47 UTC, zsloan112 approved these changes
Looks good from my end

2022-07-11 03:30 UTC, sriniva5 approved these changes

2022-07-11 03:34 UTC, merged