add more efficient fetch function and fixed dateSelection bug
umgc/summer2022 pull request #27
Opened 2022-07-20 03:30 UTC by shanefirnekas

2022-07-20 17:18 UTC, bandrews20 approved these changes
Reveiwed

2022-07-20 17:38 UTC, bandrews20 requested changes, later dismissed
Per Stanley, there are issues to the login screen

2022-07-20 23:51 UTC, stanley-dejesus approved these changes

2022-07-20 23:52 UTC, stanley-dejesus approved these changes

2022-07-21 00:06 UTC, stanley-dejesus commented
@bandrews20 - I reviewed it again, and it works as Shane mentioned...  I don't have any explanation, but my emulator working correctly now.   Please re-review, approve and merge when ready.  Thanks in advance.

- Stanley

2022-07-21 00:10 UTC, ItsDang approved these changes

2022-07-21 00:11 UTC, merged